apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-projet-web
  namespace: mini-projet-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-projet-web
  template:
    metadata:
      labels:
        app: mini-projet-web
    spec:
      containers:
        - name: mini-projet-web
          image: fatimazahrasr/appweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "üß≠ Attente que le nom DNS de MySQL soit r√©solu...";
              until getent hosts mysql-service; do
                echo "‚ùå DNS pas encore pr√™t. Attente...";
                sleep 2;
              done;

              echo "‚úÖ DNS r√©solu. V√©rification du port 3306...";
              until nc -z mysql-service 3306; do
                echo "‚è≥ Port MySQL pas encore pr√™t. Attente...";
                sleep 2;
              done;

              echo "üöÄ Lancement de Django...";
              python manage.py migrate && python manage.py runserver 0.0.0.0:8000
